name: Sync addon metadata translations

on:
  push:
    branches: [ master, main ]
    paths:
      - '**addon.xml'
      - '**resource.language.**strings.po'

jobs:
  default:
    if: github.repository == 'anxdpanic/plugin.video.youtube'

    runs-on: ubuntu-latest

    strategy:

      fail-fast: false
      matrix:
        python-version: [ 3.9 ]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: project

      - name: Checkout sync_addon_metadata_translations repository
        uses: actions/checkout@v4
        with:
          repository: xbmc/sync_addon_metadata_translations
          path: sync_addon_metadata_translations

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sync_addon_metadata_translations/

      - name: Run sync-addon-metadata-translations
        run: |
          sync-addon-metadata-translations
        working-directory: ./project

      - name: Create PR for sync-addon-metadata-translations changes
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: Sync of addon metadata translations
          title: Sync of addon metadata translations
          body: Sync of addon metadata translations triggered by ${{ github.sha }}
          branch: amt-sync
          delete-branch: true
          path: ./project
